<a href="https://colab.research.google.com/github/Dhruv-kys/TORCH-NOTEBOOK/blob/main/tensors_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.version.cuda)

2.11.0+cu128
True
12.8


### Creating a Tensor

In [2]:
a=torch.empty(2,3)

In [3]:
type(a)

torch.Tensor

In [4]:
b = torch.zeros(2,3)

In [5]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.rand(2,3)

tensor([[0.5433, 0.8343, 0.2196],
        [0.3228, 0.6405, 0.2021]])

In [7]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

### Tensor Shape

In [9]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [10]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
x.shape

torch.Size([2, 3])

In [12]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

### Tensor Data Types

In [14]:
x.dtype

torch.int64

In [15]:
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [16]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [17]:
x.to(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Tensor Operations on GPU

In [18]:
torch.cuda.is_available()

True

In [19]:
device = torch.device('cuda')

In [20]:
device

device(type='cuda')

### CPU vs GPU

In [29]:
import time

# Size of matrix
size = 10000

# Random matrices on CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# Time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end_time = time.time()
cpu_time = end_time - start_time

print(f"Time taken on CPU: {cpu_time} seconds")

# Move matrices on GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# Time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
end_time = time.time()
gpu_time = end_time - start_time

print(f"Time taken on GPU: {gpu_time} seconds")

Time taken on CPU: 17.21718454360962 seconds
Time taken on GPU: 0.11287260055541992 seconds
